# Generated by Django 5.2.11 on 2026-03-12 03:53

import utilities.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_fms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="buffertube",
            name="stripe_color",
            field=utilities.fields.ColorField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name="buffertubetemplate",
            name="stripe_color",
            field=utilities.fields.ColorField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name="ribbon",
            name="stripe_color",
            field=utilities.fields.ColorField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name="ribbontemplate",
            name="stripe_color",
            field=utilities.fields.ColorField(blank=True, max_length=6),
        ),
    ]
