# Generated by Django 5.2.11 on 2026-03-12 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0226_modulebay_rebuild_tree"),
        ("netbox_fms", "0004_spliceproject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spliceplan",
            name="mode",
        ),
        migrations.RemoveField(
            model_name="spliceplan",
            name="tray",
        ),
        migrations.AddField(
            model_name="spliceplan",
            name="cached_diff",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spliceplan",
            name="diff_stale",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="spliceplan",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plans",
                to="netbox_fms.spliceproject",
            ),
        ),
        migrations.AlterField(
            model_name="spliceplan",
            name="closure",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="splice_plan", to="dcim.device"
            ),
        ),
    ]
