# Generated by Django 5.2.11 on 2026-03-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_fms', '0007_closurecableentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='closurecableentry',
            name='entrance_label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
