# Generated by Django 5.2.11 on 2026-03-15 17:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0226_modulebay_rebuild_tree"),
        ("netbox_fms", "0010_drop_entrance_port"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fiberpathloss",
            unique_together={("cable", "wavelength_nm")},
        ),
    ]
