# Generated by Django 5.2.11 on 2026-03-17 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0226_modulebay_rebuild_tree"),
        ("netbox_fms", "0014_copy_front_port_to_front_port_a"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fiberstrand",
            name="front_port",
        ),
        migrations.AddField(
            model_name="fiberstrand",
            name="front_port_b",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fiber_strands_b",
                to="dcim.frontport",
            ),
        ),
    ]
