# Generated by Django 5.2.11 on 2026-03-17 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_fms', '0015_drop_front_port_add_front_port_b'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FiberPathLoss',
        ),
    ]
