# Generated by Django 5.2.11 on 2026-03-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_fms", "0019_fibercabletype_buffer_tube_template_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spliceplanentry",
            name="is_express",
            field=models.BooleanField(default=False),
        ),
    ]
