# Generated by Django 5.2.11 on 2026-03-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_fms', '0022_wavelengthservice_wdmdevicetypeprofile_wdmnode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fibercabletype',
            name='construction_image',
            field=models.ImageField(blank=True, upload_to='fibercabletype-images'),
        ),
    ]
