# Generated by Django 5.2.11 on 2026-03-23 03:38

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0226_modulebay_rebuild_tree"),
        ("extras", "0134_owner"),
        ("netbox_fms", "0023_fibercabletype_construction_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrayProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("tray_role", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "module_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tray_profile", to="dcim.moduletype"
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "tray profile",
                "verbose_name_plural": "tray profiles",
                "ordering": ("module_type",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
