# Generated by Django 5.2.11 on 2026-03-23 03:46

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0226_modulebay_rebuild_tree"),
        ("extras", "0134_owner"),
        ("netbox_fms", "0024_trayprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="TubeAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("position", models.PositiveIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "buffer_tube",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tray_assignments",
                        to="netbox_fms.buffertube",
                    ),
                ),
                (
                    "closure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tube_assignments", to="dcim.device"
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
                (
                    "tray",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tube_assignments", to="dcim.module"
                    ),
                ),
            ],
            options={
                "verbose_name": "tube assignment",
                "verbose_name_plural": "tube assignments",
                "ordering": ("closure", "tray", "position"),
                "unique_together": {("closure", "buffer_tube")},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
