# Generated by Django 5.2.11 on 2026-03-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_fms", "0025_tubeassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="trayprofile",
            name="max_fibers",
            field=models.PositiveIntegerField(default=24),
        ),
    ]
