# Generated by Django 5.2.11 on 2026-03-24 13:04

import utilities.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_fms", "0026_add_trayprofile_max_fibers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="buffertube",
            old_name="stripe_color",
            new_name="marker_color",
        ),
        migrations.RenameField(
            model_name="buffertubetemplate",
            old_name="stripe_color",
            new_name="marker_color",
        ),
        migrations.RenameField(
            model_name="ribbon",
            old_name="stripe_color",
            new_name="marker_color",
        ),
        migrations.RenameField(
            model_name="ribbontemplate",
            old_name="stripe_color",
            new_name="marker_color",
        ),
        migrations.AddField(
            model_name="buffertube",
            name="marker_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="buffertube",
            name="marker_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="buffertubetemplate",
            name="marker_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="buffertubetemplate",
            name="marker_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="buffertubetemplate",
            name="strand_marker_color",
            field=utilities.fields.ColorField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name="buffertubetemplate",
            name="strand_marker_interval",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="buffertubetemplate",
            name="strand_marker_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="fibercabletype",
            name="strand_marker_color",
            field=utilities.fields.ColorField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name="fibercabletype",
            name="strand_marker_interval",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fibercabletype",
            name="strand_marker_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="fiberstrand",
            name="marker_color",
            field=utilities.fields.ColorField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name="fiberstrand",
            name="marker_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fiberstrand",
            name="marker_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="ribbon",
            name="marker_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ribbon",
            name="marker_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="ribbontemplate",
            name="marker_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ribbontemplate",
            name="marker_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="ribbontemplate",
            name="strand_marker_color",
            field=utilities.fields.ColorField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name="ribbontemplate",
            name="strand_marker_interval",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ribbontemplate",
            name="strand_marker_type",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
