# Generated by Django 5.2.11 on 2026-03-24 13:07

from django.db import migrations


def migrate_stripe_to_marker(apps, schema_editor):
    for model_name in ("BufferTubeTemplate", "BufferTube", "RibbonTemplate", "Ribbon"):
        Model = apps.get_model("netbox_fms", model_name)
        Model.objects.exclude(marker_color="").update(marker_type="stripe", marker_count=1)


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_fms", "0027_rename_stripe_color_buffertube_marker_color_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_stripe_to_marker, migrations.RunPython.noop),
    ]
