# Generated by Django 5.2.11 on 2026-03-24 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0226_modulebay_rebuild_tree"),
        ("netbox_fms", "0028_marker_data_migration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spliceplan",
            options={
                "ordering": ("closure", "name"),
                "permissions": [("approve_spliceplan", "Can approve/reject splice plans")],
            },
        ),
        migrations.AddField(
            model_name="spliceplan",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="spliceplanentry",
            name="change_note",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="spliceplan",
            name="closure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="splice_plans", to="dcim.device"
            ),
        ),
    ]
