# Generated by Django 5.2.13 on 2026-05-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_fms', '0031_remove_wdm_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='fibercabletype',
            name='outer_diameter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fibercabletype',
            name='twist_factor_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
