# Generated by Django 5.2.13 on 2026-05-07 20:30

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_fms', '0033_mark_unit_marks_installer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fibercabletype',
            name='fiber_type',
        ),
        migrations.RemoveField(
            model_name='fibercircuitpath',
            name='calculated_loss_db',
        ),
        migrations.CreateModel(
            name='FiberAttenuationSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('wavelength_nm', models.PositiveSmallIntegerField()),
                ('max_loss_db_per_km', models.DecimalField(decimal_places=4, max_digits=6)),
                ('fiber_cable_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attenuation_specs', to='netbox_fms.fibercabletype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'fiber attenuation spec',
                'verbose_name_plural': 'fiber attenuation specs',
                'ordering': ('fiber_cable_type', 'wavelength_nm'),
                'unique_together': {('fiber_cable_type', 'wavelength_nm')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
