# Generated by Django 6.0.6 on 2026-07-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_fms', '0034_remove_fibercabletype_fiber_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fibercabletype',
            name='color_scheme',
            field=models.CharField(default='eia_598', max_length=20),
        ),
    ]
