# Generated by Django 6.1 on 2026-09-23 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circuits", "0060_denormalization_triggers"),
        ("dcim", "0250_cooling_infrastructure"),
        ("netbox_fms", "0035_fibercabletype_color_scheme"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="fibercircuitnode",
            name="fibercircuitnode_exactly_one_ref",
        ),
        migrations.AddField(
            model_name="fibercircuit",
            name="provider_circuits",
            field=models.ManyToManyField(blank=True, related_name="fiber_circuits", to="circuits.circuit"),
        ),
        migrations.AddField(
            model_name="fibercircuitnode",
            name="provider_circuit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fiber_circuit_nodes",
                to="circuits.circuit",
            ),
        ),
        migrations.AddConstraint(
            model_name="fibercircuitnode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("cable__isnull", False),
                        ("fiber_strand__isnull", True),
                        ("front_port__isnull", True),
                        ("provider_circuit__isnull", True),
                        ("rear_port__isnull", True),
                        ("splice_entry__isnull", True),
                    ),
                    models.Q(
                        ("cable__isnull", True),
                        ("fiber_strand__isnull", True),
                        ("front_port__isnull", False),
                        ("provider_circuit__isnull", True),
                        ("rear_port__isnull", True),
                        ("splice_entry__isnull", True),
                    ),
                    models.Q(
                        ("cable__isnull", True),
                        ("fiber_strand__isnull", True),
                        ("front_port__isnull", True),
                        ("provider_circuit__isnull", True),
                        ("rear_port__isnull", False),
                        ("splice_entry__isnull", True),
                    ),
                    models.Q(
                        ("cable__isnull", True),
                        ("fiber_strand__isnull", False),
                        ("front_port__isnull", True),
                        ("provider_circuit__isnull", True),
                        ("rear_port__isnull", True),
                        ("splice_entry__isnull", True),
                    ),
                    models.Q(
                        ("cable__isnull", True),
                        ("fiber_strand__isnull", True),
                        ("front_port__isnull", True),
                        ("provider_circuit__isnull", True),
                        ("rear_port__isnull", True),
                        ("splice_entry__isnull", False),
                    ),
                    models.Q(
                        ("cable__isnull", True),
                        ("fiber_strand__isnull", True),
                        ("front_port__isnull", True),
                        ("provider_circuit__isnull", False),
                        ("rear_port__isnull", True),
                        ("splice_entry__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="fibercircuitnode_exactly_one_ref",
            ),
        ),
    ]
