# Generated by Django 5.2.16 on 2026-07-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_fms', '0035_fibercabletype_color_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='fibercabletype',
            name='front_port_label_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fibercabletype',
            name='front_port_name_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fibercabletype',
            name='rear_port_label_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fibercabletype',
            name='rear_port_name_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fibercabletype',
            name='strand_name_template',
            field=models.TextField(blank=True),
        ),
    ]
