# Generated by Django 6.1 on 2026-10-06 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0056_gfk_indexes'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0226_add_mptt_tree_indexes'),
        ('netbox_fms', '0038_backfill_adopted_cable_connectors'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiberStrandPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('end_a_kind', models.CharField(default='open', max_length=20)),
                ('end_b_kind', models.CharField(default='open', max_length=20)),
                ('end_a_reason', models.CharField(blank=True, max_length=20)),
                ('end_b_reason', models.CharField(blank=True, max_length=20)),
                ('completeness', models.CharField(db_index=True, default='open_open', max_length=30)),
                ('route_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_proposed', models.BooleanField(default=False)),
                ('is_defective', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField()),
                ('end_a_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiber_path_ends_a', to='dcim.frontport')),
                ('end_b_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiber_path_ends_b', to='dcim.frontport')),
            ],
            options={
                'verbose_name': 'fiber path',
                'verbose_name_plural': 'fiber paths',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='PathAnalysisQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiber_path_analysis_queue', to='dcim.device')),
            ],
            options={
                'verbose_name': 'path analysis queue entry',
                'verbose_name_plural': 'path analysis queue entries',
                'ordering': ('created', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='PathAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=30)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('front_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiber_path_anomalies', to='dcim.frontport')),
                ('strand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='path_anomalies', to='netbox_fms.fiberstrand')),
            ],
            options={
                'verbose_name': 'path anomaly',
                'verbose_name_plural': 'path anomalies',
                'ordering': ('-detected_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='RouteChangeAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('source_id', models.PositiveBigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_change_authorizations', to='netbox_fms.fibercircuit')),
                ('source_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('created', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='FiberStrandPathHop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('cable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiber_path_hops', to='dcim.cable')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hops', to='netbox_fms.fiberstrandpath')),
                ('provider_circuit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiber_path_hops', to='circuits.circuit')),
                ('strand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='path_hops', to='netbox_fms.fiberstrand')),
            ],
            options={
                'ordering': ('path', 'position'),
                'constraints': [models.UniqueConstraint(fields=('path', 'position'), name='fiberstrandpathhop_unique_position'), models.CheckConstraint(condition=models.Q(models.Q(('cable__isnull', True), ('provider_circuit__isnull', True), ('strand__isnull', False)), models.Q(('cable__isnull', False), ('provider_circuit__isnull', True), ('strand__isnull', True)), models.Q(('cable__isnull', True), ('provider_circuit__isnull', False), ('strand__isnull', True)), _connector='OR'), name='fiberstrandpathhop_exactly_one_ref')],
            },
        ),
    ]
